// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/login" | "/management" | "/matches" | "/matches/[id]" | "/matches/[id]/referee" | "/my-team" | "/players/[id]" | "/profile" | "/referee" | "/social" | "/teams" | "/teams/[id]" | "/teams/[id]/edit" | "/tournaments" | "/tournaments/[id]" | "/tournaments/winners" | "/users"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/login": {}
  "/management": {}
  "/matches": {}
  "/matches/[id]": { "id": string; }
  "/matches/[id]/referee": { "id": string; }
  "/my-team": {}
  "/players/[id]": { "id": string; }
  "/profile": {}
  "/referee": {}
  "/social": {}
  "/teams": {}
  "/teams/[id]": { "id": string; }
  "/teams/[id]/edit": { "id": string; }
  "/tournaments": {}
  "/tournaments/[id]": { "id": string; }
  "/tournaments/winners": {}
  "/users": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
