// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../src/app/(main)/management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/management">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/matches/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/matches/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/matches/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/matches/[id]/referee/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/matches/[id]/referee">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/matches/[id]/referee/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/matches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/matches">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/matches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/my-team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my-team">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/my-team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/players/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/players/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/players/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/referee/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referee">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/referee/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/social/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/social">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/social/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/teams/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teams/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/teams/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/teams/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teams/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/teams/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/teams/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teams">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/teams/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/tournaments/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tournaments/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/tournaments/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/tournaments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tournaments">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/tournaments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/tournaments/winners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tournaments/winners">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/tournaments/winners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(main)/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/users">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../src/app/(main)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(main)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
