/**
 * Form labels and field placeholders used throughout the application.
 */

export const LABELS = {
  auth: {
    email: 'Email',
    password: 'Contraseña',
    confirmPassword: 'Confirmar contraseña',
    name: 'Nombre',
    lastName: 'Apellido',
    dni: 'DNI',
    phone: 'Teléfono',
    role: 'Rol',
    login: 'Iniciar sesión',
    register: 'Registrarse',
    loginWithGoogle: 'Continuar con Google',
    forgotPassword: '¿Olvidaste tu contraseña?',
    noAccount: '¿No tenés cuenta?',
    hasAccount: '¿Ya tenés cuenta?',
  },
  team: {
    name: 'Nombre del equipo',
    nameShort: 'Nombre corto',
    description: 'Descripción',
    city: 'Ciudad',
    state: 'Provincia',
    country: 'País',
    stadium: 'Estadio',
    category: 'Categoría',
    division: 'División',
    president: 'Presidente',
    coach: 'Director Técnico',
    players: 'Jugadores',
    createTeam: 'Crear equipo',
    editTeam: 'Editar equipo',
  },
  player: {
    position: 'Posición',
    number: 'Número',
    status: 'Estado',
    goals: 'Goles',
    fouls: 'Faltas',
    yellowCards: 'Tarjetas amarillas',
    redCards: 'Tarjetas rojas',
    matchesPlayed: 'Partidos jugados',
  },
  match: {
    date: 'Fecha',
    time: 'Horario',
    stadium: 'Estadio',
    referee: 'Árbitro',
    status: 'Estado',
    homeTeam: 'Equipo local',
    awayTeam: 'Equipo visitante',
    lineup: 'Alineación',
    events: 'Eventos',
  },
  tournament: {
    name: 'Nombre del torneo',
    dateStart: 'Fecha de inicio',
    dateEnd: 'Fecha de finalización',
    standings: 'Tabla de posiciones',
    matches: 'Partidos',
    teams: 'Equipos',
    prizes: 'Premios',
  },
  common: {
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    create: 'Crear',
    search: 'Buscar...',
    loading: 'Cargando...',
    noResults: 'No se encontraron resultados.',
    viewMore: 'Ver más',
    viewAll: 'Ver todos',
    back: 'Volver',
  },
} as const;
